-- 코드를 입력하세요
SELECT A.AUTHOR_ID as AUTHOR_ID, A.AUTHOR_NAME as AUTHOR_NAME, B.CATEGORY as CATEGORY, SUM(SALES*PRICE)as TOTAL_SALES 
FROM BOOK_SALES BS 
    JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE like '2022-01-%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC
