SELECT TMP.AUTHOR_ID, A.AUTHOR_NAME, TMP.CATEGORY, TMP.TOTAL_SALES
FROM (
    SELECT AUTHOR_ID, CATEGORY, SUM(B.PRICE * BS.SALES) as TOTAL_SALES
    FROM BOOK B
        JOIN (
            SELECT *
            FROM BOOK_SALES
            WHERE SALES_DATE LIKE '2022-01%'
            ) BS ON B.BOOK_ID = BS.BOOK_ID
    GROUP BY B.AUTHOR_ID, B.CATEGORY
    ) as TMP
    JOIN AUTHOR A ON TMP.AUTHOR_ID = A.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC