SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I
    JOIN (
            SELECT FOOD_TYPE, MAX(FAVORITES) as MAX_FAV
            FROM REST_INFO
            GROUP BY FOOD_TYPE
    ) MF ON I.FOOD_TYPE = MF.FOOD_TYPE
WHERE I.FAVORITES = MF.MAX_FAV
ORDER BY FOOD_TYPE DESC;
