SELECT NAME, DATETIME
FROM ANIMAL_INS I
WHERE NOT EXISTS (SELECT ANIMAL_ID
                            FROM ANIMAL_OUTS O
                            WHERE I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY I.DATETIME ASC
LIMIT 3;
