SELECT T.FLAVOR
FROM (SELECT FH.FLAVOR, SUM(J.TOTAL_ORDER + FH.TOTAL_ORDER) as TOTAL
      FROM FIRST_HALF FH
      JOIN JULY J ON FH.FLAVOR = J.FLAVOR
      GROUP BY FLAVOR
      ORDER BY TOTAL DESC) as T
LIMIT 3;