-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, TMP.TOTAL_SALES
FROM USED_GOODS_USER U,
    (SELECT WRITER_ID, STATUS, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000) TMP
WHERE U.USER_ID = TMP.WRITER_ID
ORDER BY TMP.TOTAL_SALES