WITH RENTAL_CNT AS (
    SELECT CAR_ID, COUNT(*) as CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(H.START_DATE), H.CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN RENTAL_CNT C ON H.CAR_ID = C.CAR_ID
WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY H.CAR_ID, MONTH(H.START_DATE)
ORDER BY MONTH(H.START_DATE), H.CAR_ID DESC