SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, (N.MAX_SIZE - SIZE_OF_COLONY) as YEAR_DEV, ID
FROM ECOLI_DATA E
    JOIN (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
          FROM ECOLI_DATA
          GROUP BY YEAR(DIFFERENTIATION_DATE)) N ON YEAR(E.DIFFERENTIATION_DATE) = N.YEAR
ORDER BY YEAR, YEAR_DEV