SELECT I.ID as ID, N.FISH_NAME as FISH_NAME, I.LENGTH as LENGTH
FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
        FROM FISH_INFO
        GROUP BY FISH_TYPE) M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LEN
ORDER BY I.ID