SELECT B.CATEGORY, SUM(BS.SALES) as TOTAL_SALES
FROM BOOK B
    JOIN (
        SELECT *
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE '2022-01%') BS ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC