
SELECT P.CATEGORY, P.PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
    JOIN (SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY) as TMP
        ON P.CATEGORY = TMP.CATEGORY
WHERE P.CATEGORY in ('과자', '국', '김치', '식용유')
    AND P.PRICE = TMP.MAX_PRICE
ORDER BY PRICE DESC
